repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
    args: ['--unsafe'] # avoid problems with mkdocs mermaid extension
    stages:
    - commit
  - id: check-toml
    stages:
    - commit
  - id: end-of-file-fixer
    exclude: |
        (?x)^(
            {{_copier_conf.answers_file}}|
            docs/licenses.md
        )$
    stages:
    - commit
  - id: trailing-whitespace
    exclude: |
        (?x)^(
            {{_copier_conf.answers_file}}|
            docs/licenses.md
        )$
    stages:
    - commit
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.4
  hooks:
  - id: ruff
    args: [ --fix ]
    stages:
    - commit
  - id: ruff-format
    stages:
    - commit
- repo: https://github.com/econchick/interrogate
  rev: 1.5.0
  hooks:
  - id: interrogate
    stages:
    - commit
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: '3.0.0'
  hooks:
  - id: forbid-binary
    stages:
    - commit
- repo: https://github.com/FHPythonUtils/LicenseCheck
  rev: '2024.1.5'
  hooks:
  - id: licensecheck
    stages:
    - commit
