repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml
    args: ['--unsafe'] # avoid problems with mkdocs mermaid extension
    stages:
    - pre-commit
  - id: check-toml
    stages:
    - pre-commit
  - id: end-of-file-fixer
    stages:
    - pre-commit
  - id: trailing-whitespace
    stages:
    - pre-commit
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: '3.0.0'
  hooks:
  - id: forbid-binary
    stages:
    - pre-commit
- repo: local
  hooks:
  - id: uv-lock
    name: uv-lock
    entry: uv lock
    language: python
    files: ^(uv\.lock|pyproject\.toml)$
    pass_filenames: false
    stages:
    - pre-commit
  - id: ruff
    name: ruff
    entry: uv run ruff check
    args: [ --fix ]
    language: system
    types: [file, python]
    stages:
    - pre-commit
  - id: ruff-format
    name: ruff-format
    entry: uv run ruff format
    language: system
    types: [file, python]
    stages:
    - pre-commit
  - id: interrogate
    name: interrogate
    entry: uv run interrogate
    language: system
    types: [file, python]
    stages:
    - pre-commit
  - id: pydoclint
    name: pydoclint
    entry: uv run pydoclint
    language: system
    types: [file, python]
    stages:
    - pre-commit
