repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
    args: ['--unsafe'] # avoid problems with mkdocs mermaid extension
    stages:
    - commit
  - id: check-toml
    stages:
    - commit
  - id: end-of-file-fixer
    exclude: |
        (?x)^(
            {{_copier_conf.answers_file}}|
            docs/licenses.md
        )$
    stages:
    - commit
  - id: trailing-whitespace
    exclude: |
        (?x)^(
            {{_copier_conf.answers_file}}|
            docs/licenses.md
        )$
    stages:
    - commit
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: '3.0.0'
  hooks:
  - id: forbid-binary
    stages:
    - commit
- repo: local
  hooks:
  - id: ruff
    name: ruff
    entry: poetry run ruff
    args: [ --fix ]
    language: system
    types: [file, python]
    stages:
    - commit
  - id: ruff-format
    name: ruff-format
    entry: poetry run ruff format
    language: system
    types: [file, python]
    stages:
    - commit
  - id: interrogate
    name: interrogate
    entry: poetry run interrogate
    language: system
    types: [file, python]
    stages:
    - commit
  - id: licensecheck
    name: licensecheck
    entry: poetry run licensecheck
    args: [ --zero ]
    language: system
    pass_filenames: false
    stages:
    - commit
