[defaults]
project_name = "A new Project"
project_description = "Not much."
author = "Excidion"
author_email = "36995046+Excidion@users.noreply.github.com"
ci = ""

[output.".ctt/test"]
python_version = "3.10"
use_dvc = false
