[project]
name = "reproML"
version = "0.1.0"
description = "A template for collaborative development and reproducible results in data science and machine learning projects."
authors = ["Excidion <36995046+Excidion@users.noreply.github.com>"]
readme = "README.md"
license = "Apache 2.0"
requires-python = ">=3.10.9"
dependencies = [
    "interrogate>=1.7.0",
    "logdecorator>=2.5",
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-jupyter>=0.25.0",
    "mkdocs-literate-nav>=0.6.1",
    "mkdocs-material>=9.5.35",
    "mkdocstrings[python]>=0.26.1",
]

[dependency-groups]
dev = [
    "pre-commit>=4.0.1",
    "pydoclint>=0.8.3",
    "ruff>=0.6.6",
    "ty>=0.0.7",
]
test = [
    "copier-template-tester>=2.1.4",
]

[tool.interrogate]
style = "google"
ignore-init-module = true
ignore-module = true
fail-under = 100
verbose = 1
generate-badge = "reproML/docs/helper"
badge-format = "svg"

[tool.pydoclint]
style = "google"
skip-checking-short-docstrings = false
