name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Move README to docs
        run: cp README.md docs/index.md

      - name: Install jinja
        run: pip install jinja2-cli

      - name: Render pyproject.toml
        run: jinja2 pyproject.toml.jinja -D author=Excidion -D author_email=none@none.org -D license="Apache 2.0" > pyproject.toml

      - name: Render mkdocs.yml
        run: jinja2 mkdocs.yml.jinja -D project_name=reproML -D repo_url=https://github.com/Excidion/reproML/ > mkdocs.yml

      - name: Setup environment
        run: pip install poetry && poetry install --only dev,docs

      - name: Run checks
        run: poetry run pre-commit run --all-files

      - name: Deploy docs
        run: poetry run mkdocs gh-deploy --force
