name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Move README to docs
        run: cp README.md reproML/docs/index.md

      - name: Setup environment
        run: pip install uv && uv sync --all-extras

      - name: Run checks
        run: uv run pre-commit run --all-files

      - name: Deploy docs
        run: uv run mkdocs gh-deploy --force
