name: Test template
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "main"

jobs:
  test-template:
    name: Test template
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python_version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
        ci:
          - ""
          - github
        use_dvc:
          - true
          - false
        remote_type:
          - ""
          - all
        # don't use those combinations to create a job
        exclude:
          - use_dvc: false
            remote_type: all

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Export test values
        uses: easyware-io/export-to-env@v1
        with:
          vars: ${{ toJSON(matrix) }}
          prefix: MATRIX_

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Write test config
        run: |
            uv run scripts/substitute_env.py ctt.toml.template ctt.toml
            cat ctt.toml

      - name: Install dependencies
        run: uv sync --frozen --only-group test

      - name: Test template
        run: uv run ctt

      - name: Test docs build
        working-directory: .ctt/test/
        run: uv run mkdocs build --strict
